### ISSUE TITLE
ModuleNotFoundError for breathpy

### ISSUE THREAD

**Issue by abhatia15** [philmaweb/breathpy#1]
I installed the breathpy module using pip, conda environment was created with Python 3.8, but when running the following from breathpy/breathpy/tutorial/binary_candy.ipynb, I'm getting ModuleNotFoundError. Any suggestions how to resolve this?

`from breathpy.generate_sample_data import generate_train_test_sets, generate_train_test_set_helper`

**Comment by philmaweb** [comment]
Hi, are you using the same anaconda environment to run your jupyter notebook that you installed breathpy?
In your jupyter notebook, could you add a cell and execute `!conda list` or `!conda list | grep breathpy` if you're on linux? 
 
![image](https://user-images.githubusercontent.com/4519362/149681761-2198cb30-87ce-4d86-a90f-cde8f7953c25.png)

**Comment by abhatia15** [comment]
Hi, thanks for the response! Yes, I am using the same anaconda environment (`breath`) for Jupyter notebook that I had used to install breathpy. I had used these commands to create the environment and install breathpy.
```
conda create --name breath python=3.8 pip graphviz -y
conda activate breath
pip install breathpy
```

But `!conda list | grep breathpy` does not show anything in the Jupyter notebook. I also tried `conda list | grep breathpy` in the terminal with `breath` activated, but I do not see breathpy even there in the list. Did I miss a step?

**Comment by philmaweb** [comment]
It looks like the conda version you run is not the same that you used to install `breathpy`. Maybe also check with `conda list` whether you can find breathpy. Could you also check which pip you used to install it? I.e. `which pip`. Maybe `pip3` is the version installed with your conda?

**Comment by abhatia15** [comment]
Hi, thanks. I uninstalled and installed again with pip3, but got the same error. Then I uninstalled it again and installed with pip and tried but it's the same issue. I have breathpy installed:
```
$ pip show breathpy
Name: breathpy
Version: 0.9.1
Summary: Breath analysis in python
Home-page: https://github.com/philmaweb/breathpy
Author: Philipp Weber
Author-email: pweber@imada.sdu.dk
License: GPLv3
Location: ...
```

I checked the following in the Python console and it seems that I am able to import breathpy but not modules under it, please see the following:
```
$ python
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from breathpy.model.BreathCore import construct_default_parameters, construct_default_processing_evaluation_steps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'breathpy.model'
>>> import breathpy
>>> from breathpy.generate_sample_data import generate_train_test_sets, generate_train_test_set_helper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'breathpy.generate_sample_data'
>>> 
```

I was wondering if it could be an issue with the package itself or if not, do you have a suggestion how to resolve this?

**Comment by philmaweb** [comment]
Thanks for the updated report. 
You seem to run into issues on mac. Maybe we can find out what's causing it. But I don't have a mac available so you'll have to help me out here. 

It looks like importing `breathpy` in general works - could you first try to upgrade the library to the recent version 0.9.6?
`pip install --upgrade breathpy` should upgrade you to version 0.9.6. 

Please verify that your pip, python and jupyter all point to the same conda environment (in my case breath).
```
(breath) $ which pip
/home/pweber/anaconda3/envs/breath/bin/pip
(breath) $ which python
/home/pweber/anaconda3/envs/breath/bin/python
(breath) $ which jupyter
/home/pweber/anaconda3/envs/breath/bin/jupyter
``` 

Next we'll verify the installation path of `breathpy`.  
Start a python shell and check where `breathpy` is installed, and whether you can load it's submodules without an error.
For me this looks like this:  
```
(breath) $ python
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import breathpy
>>> breathpy.__version__
'0.9.6'
>>> breathpy.__path__
['/home/pweber/anaconda3/envs/breath/lib/python3.8/site-packages/breathpy']
>>> from breathpy.model.BreathCore import construct_default_parameters
>>>
```

**Comment by abhatia15** [comment]
Thanks, Philipp! pip, python and jupyter all point to the same environment. 

```
(breath) aBhatia-MBP-16:breath abhatia$ which pip
/Users/abhatia/opt/anaconda3/envs/breath/bin/pip
(breath) aBhatia-MBP-16:breath abhatia$ which python
/Users/abhatia/opt/anaconda3/envs/breath/bin/python
(breath) aBhatia-MBP-16:breath abhatia$ which jupyter
/Users/abhatia/opt/anaconda3/envs/breath/bin/jupyter
```

But when I try to install version 0.9.6 of breathpy, I get this error:
```
ERROR: Could not find a version that satisfies the requirement pyopenms==2.5.0 (from breathpy) (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64, 2.6.0, 2.7.0)
ERROR: No matching distribution found for pyopenms==2.5.0
```

I tried to install pyopenms 2.5.0 but that version is not available, I have version 2.7.0 installed by default now but with the default version of pyopenms, I get the above error when installing breathpy 0.9.6:
```
(breath) aBhatia-MBP-16:breath abhatia$ pip install pyopenms==2.5.0
ERROR: Could not find a version that satisfies the requirement pyopenms==2.5.0 (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64, 2.6.0, 2.7.0)
ERROR: No matching distribution found for pyopenms==2.5.0
(breath) aBhatia-MBP-16:breath abhatia$ pip install pyopenms
...
Successfully installed numpy-1.22.2 pyopenms-2.7.0
```
